name: 'buildx-3.13'
on:
  push:
#    branches: [ master ]
    paths:
    - 3.13/Dockerfile
  pull_request:
    branches: [ master ]
  schedule:
  # 每月25号，4:12 执行一次
    - cron: '12 4 25 * *'
  # 每周六，4:33 执行一次，以同步官方 alpine 3.13
  #  - cron: '33 4 * * SAT'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  buildx-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # 设置 QEMU 以支持多个平台
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # 设置 buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # 配置缓存
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      # 登录 dockerhub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # 编译并推送到 dockerhub
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: 3.13
          file: Dockerfile
          platforms: linux/386,linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          tags: |
            ryjer/alpine:3.13
      # 处理缓存无限增大问题的临时修复，以防出现问题。（等待github官方修复）
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
